name: LEGO diario

on:
  schedule:
    - cron: "0 17 * * *"   # 11:00 AM CDMX (GitHub Actions usa UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lego-daily
  cancel-in-progress: true

jobs:
  send-lego:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: America/Mexico_City
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Instalar dependencias
        run: npm ci --no-audit --fund=false

      - name: Enviar LEGO
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          AFF_PREFIX: ${{ secrets.AFF_PREFIX }}   # opcional
          LEGO_MAX_ITEMS: "12"
          LEGO_MIN_DISCOUNT: "5"
        run: node bot_lego.mjs send
